
import { Project, Task, TimeBlock } from './TaskTypes';

export const sampleProjects: Project[] = [
  { id: "project-1", name: "Personal", description: "Personal and errands", isExpanded: true },
  { id: "project-2", name: "Work", description: "Tasks for work", isExpanded: true },
  { id: "project-3", name: "Fitness", description: "Workout routines", isExpanded: true },
  { id: "project-4", name: "Learning", description: "Courses and study", isExpanded: true },
];

export const sampleTasks: Task[] = [
  {
    id: "task-1-1",
    title: "Buy groceries",
    description: "Get vegetables, fruits, snacks",
    priority: "medium",
    projectId: "project-1",
    dueDate: new Date(Date.now() - 48 * 60 * 60 * 1000), // overdue
    notes: "",
    estimatedTime: 45,
    timeTracked: 0,
    children: [
      { id: "task-1-1-1", title: "Buy apples", priority: "low", projectId: "project-1", parentId: "task-1-1", timeTracked: 0, children: [] },
      { id: "task-1-1-2", title: "Buy broccoli", priority: "medium", projectId: "project-1", parentId: "task-1-1", timeTracked: 0, children: [] },
    ],
    isExpanded: true,
  },
  {
    id: "task-1-2",
    title: "Clean living room",
    description: "Vacuum and dust all surfaces",
    priority: "high",
    projectId: "project-1",
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    notes: "",
    estimatedTime: 30,
    timeTracked: 0,
    children: [],
  },
  {
    id: "task-1-3",
    title: "Call plumber",
    description: "Fix bathroom sink",
    priority: "low",
    projectId: "project-1",
    notes: "",
    estimatedTime: 15,
    timeTracked: 0,
    children: [],
  },
  {
    id: "task-2-1",
    title: "Prepare Q2 slides",
    description: "Q2 presentation deck",
    priority: "high",
    projectId: "project-2",
    dueDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    notes: "",
    estimatedTime: 80,
    timeTracked: 0,
    children: [],
  },
  {
    id: "task-2-2",
    title: "Send invoices",
    description: "For Q1 clients",
    priority: "medium",
    projectId: "project-2",
    notes: "",
    estimatedTime: 20,
    timeTracked: 0,
    children: [],
  },
  {
    id: "task-2-3",
    title: "Review PRs",
    description: "Check merged pull requests",
    priority: "low",
    projectId: "project-2",
    notes: "",
    estimatedTime: 50,
    timeTracked: 0,
    children: [],
  },
  {
    id: "task-3-1",
    title: "Morning run",
    description: "5km run in park",
    priority: "medium",
    projectId: "project-3",
    dueDate: new Date(Date.now() + 24 * 60 * 60 * 1000),
    notes: "",
    estimatedTime: 40,
    timeTracked: 0,
    children: [],
  },
  {
    id: "task-3-2",
    title: "Yoga session",
    description: "Evening yoga",
    priority: "low",
    projectId: "project-3",
    notes: "",
    estimatedTime: 60,
    timeTracked: 0,
    children: [],
  },
  {
    id: "task-3-3",
    title: "Plan meals",
    description: "Healthy weekly meal plan",
    priority: "high",
    projectId: "project-3",
    notes: "",
    estimatedTime: 30,
    timeTracked: 0,
    children: [],
  },
  {
    id: "task-4-1",
    title: "Study JavaScript",
    description: "Complete function closures topic",
    priority: "high",
    projectId: "project-4",
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    notes: "",
    estimatedTime: 100,
    timeTracked: 30,
    children: [],
  },
  {
    id: "task-4-2",
    title: "Solve math quiz",
    description: "Algebra and calculus",
    priority: "medium",
    projectId: "project-4",
    notes: "",
    estimatedTime: 90,
    timeTracked: 0,
    children: [],
  },
  {
    id: "task-4-3",
    title: "Read React docs",
    description: "Hooks, effects",
    priority: "low",
    projectId: "project-4",
    notes: "",
    estimatedTime: 60,
    timeTracked: 0,
    children: [],
  }
];

export const sampleTimeBlocks: TimeBlock[] = [
  {
    id: "block-1",
    taskId: "task-4-1",
    date: new Date(),
    startTime: "10:00",
    endTime: "11:00"
  },
  {
    id: "block-2",
    taskId: "task-1-1",
    date: new Date(Date.now() - 24 * 60 * 60 * 1000),
    startTime: "08:00",
    endTime: "08:30"
  }
];
