// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wszmlinkutcinftmzedh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indzem1saW5rdXRjaW5mdG16ZWRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MDc3ODQsImV4cCI6MjA2MTI4Mzc4NH0.iUXQ_1-hRZBLGHAK8u1b0lpRgPQiqf-Qownlp95FuTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);